// @ts-check
/**
 * `npm run perf:report`: merges the per-adapter files of docs/milestones/m10/perf/ into the budget
 * table docs/milestones/m10/perf-report.md.
 *
 * The table is docs/architecture.md's performance budget, one row per budget line and one column
 * group per adapter that has been measured. A cell says what was measured and what it was
 * measured on, and a verdict only where the measurement can carry one:
 *
 * - a SwiftShader number is a software rasteriser on CPU cores: it is never judged against a GPU
 *   budget ("indicative"), except the parts that are the same code on any machine (the CPU side
 *   of a frame);
 * - the CPU engine is judged against its budget on the machine it ran on, with that machine's load
 *   stated, because it is the only adapter here whose cost is the cost;
 * - an adapter nobody has measured is "not measured" (the owner's action, docs/open-questions.md
 *   Q14), and a scenario of a milestone not yet merged is "deferred".
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { format, resolveConfig } from 'prettier';
import { ROOT } from '../gpu-test/browser.mjs';
import { BUDGET, SINGLE_GALAXY } from './scenarios.mjs';

const dir = join(ROOT, 'docs/milestones/m10/perf');
const out = join(ROOT, 'docs/milestones/m10/perf-report.md');
/** @type {any[]} */
const files = readdirSync(dir)
  .filter((f) => f.endsWith('.json'))
  .sort()
  .map((f) => JSON.parse(readFileSync(join(dir, f), 'utf8')));
const gpu = files.filter((f) => f.kind === 'gpu');
const cpu = files.find((f) => f.kind === 'cpu');
const worker = files.find((f) => f.kind === 'cpu-worker');

const ms = (/** @type {number} */ x) => (x < 10 ? x.toFixed(1) : x.toFixed(0));
const names = SINGLE_GALAXY.map((s) => s.name);
/** @param {any} f @param {string} n */
const gres = (f, n) => f.results?.find((/** @type {any} */ r) => r.name === n);
const range = (/** @type {number[]} */ xs) =>
  xs.length ? `${ms(Math.min(...xs))}–${ms(Math.max(...xs))}` : 'none';

const lines = [
  '# Performance report',
  '',
  'Generated by `npm run perf:report` from `perf/*.json`, which `npm run perf` and `npm run perf:worker` write. Do not edit by hand. **Every number carries the adapter it was measured on. No budget is claimed on real hardware: no real GPU was available (docs/open-questions.md Q14).**',
  '',
  '## What was measured on',
  '',
  '| adapter | what it is | machine | measured |',
  '| --- | --- | --- | --- |',
];
for (const f of gpu)
  lines.push(
    `| ${f.label} | ${f.adapter?.description || f.adapter?.vendor || '?'} / ${f.adapter?.architecture ?? ''}; GPU timestamps ${f.timestamps ? 'yes' : 'no (wall clock only)'} | ${f.machine.cpu}; load ${f.machine.loadBefore.join(' ')} before, ${f.machine.loadAfter.join(' ')} after; ${f.browser} | ${f.date} |`,
  );
if (cpu)
  lines.push(
    `| ${cpu.label} | the TypeScript kernels and software rasteriser, one thread of Node ${cpu.machine.node} | ${cpu.machine.cpu}; load ${cpu.machine.loadBefore.join(' ')} before, ${cpu.machine.loadAfter.join(' ')} after | ${cpu.date} |`,
  );
lines.push(
  '',
  'The machine was shared with other jobs, so every time is an upper bound for an idle one (the load averages say by how much). SwiftShader is a software rasteriser on those same CPU cores: its "GPU" times are CPU times and say nothing about a GPU.',
  '',
  '## Budget (docs/architecture.md) against what was measured',
  '',
  '| budget row | budget | adapter | measured (median over the single-galaxy scenarios; range) | verdict |',
  '| --- | --- | --- | --- | --- |',
);
for (const b of BUDGET) {
  const scen = b.scenarios === 'single' ? names : b.scenarios;
  let any = false;
  for (const f of gpu) {
    if (b.id === 'cpu-orbit') continue;
    const rs = scen.map((n) => gres(f, n)).filter(Boolean);
    if (!rs.length) continue;
    any = true;
    const vals =
      b.id.startsWith('orbit')
        ? rs.map((/** @type {any} */ r) => (r.orbit.gpuMs ?? r.orbit.latencyMs).median)
        : rs.map((/** @type {any} */ r) => r.model.firstFrameMs.median);
    const what =
      b.id.startsWith('orbit') && rs[0].orbit.gpuMs ? 'GPU timestamps' : 'wall clock';
    lines.push(
      `| ${b.row} | ${b.budget} | ${f.label} | ${range(vals)} ms (${what}) | indicative only: ${/swiftshader/i.test(f.adapterChoice) ? 'software rasteriser, not a GPU' : 'not a reference machine'} |`,
    );
  }
  if (b.id === 'cpu-orbit' && cpu) {
    const rs = scen.map((n) => cpu.results.find((/** @type {any} */ r) => r.name === n)).filter(Boolean);
    const vals = rs.map((/** @type {any} */ r) => r.orbitFrameMs.median);
    any = true;
    const over = vals.filter((v) => v >= b.limitMs).length;
    lines.push(
      `| ${b.row} | ${b.budget} | ${cpu.label} | ${range(vals)} ms (view + ink + composite) | ${over ? `exceeded in ${String(over)} of ${String(vals.length)} scenarios on this machine (load ${cpu.machine.loadBefore[0]})` : 'within budget on this machine'} |`,
    );
  }
  if (!any && Array.isArray(b.scenarios))
    lines.push(
      `| ${b.row} | ${b.budget} | - | - | deferred: ${b.scenarios.join(', ')} land with M7, M8 and M9 |`,
    );
  if (b.id !== 'cpu-orbit' && !gpu.some((f) => /^(?!.*swiftshader)/i.test(f.adapterChoice)))
    lines.push(
      `| ${b.row} | ${b.budget} | a real GPU (integrated, discrete, mobile) | - | **not measured** (owner action, Q14) |`,
    );
}

lines.push('', '## Orbit frame, per scenario', '');
for (const f of gpu) {
  lines.push(
    `### ${f.label}`,
    '',
    `Plate ${String(f.config.plateCss)} CSS px at DPR ${String(f.config.dpr)}; ${String(f.config.orbitFrames)} orbit frames and ${String(f.config.modelRuns)} model runs per scenario, medians.`,
    '',
    '| scenario | latency (awaited) ms | JS side ms | pipelined ms/frame | GPU view / ink / composite ms | buffers + bind groups created per frame | first frame after a new seed ms (scene / upload on the CPU) |',
    '| --- | --- | --- | --- | --- | --- | --- |',
  );
  for (const r of f.results) {
    const o = r.orbit;
    const p = o.gpuByPass;
    lines.push(
      `| ${r.name} | ${ms(o.latencyMs.median)} | ${ms(o.cpuSideMs.median)} | ${ms(o.pipelinedMs)} | ${p ? `${ms(p['view: project, scan, expand'] ?? 0)} / ${ms(p['present: ink'] ?? 0)} / ${ms(p['present: composite'] ?? 0)}` : 'n/a'} | ${String(o.alloc.createBuffer)} + ${String(o.alloc.createBindGroup)} | ${ms(r.model.firstFrameMs.median)} (${ms(r.model.sceneMs.median)} / ${ms(r.model.uploadMs.median)}) |`,
    );
  }
  lines.push('');
}
if (cpu) {
  lines.push(
    `### ${cpu.label}`,
    '',
    `Plate ${String(cpu.config.plateCss)} CSS px at DPR ${String(cpu.config.dpr)}; medians.`,
    '',
    '| scenario | marks | scene ms | model ms | view ms | ink ms | composite ms | orbit frame ms | first frame ms |',
    '| --- | --- | --- | --- | --- | --- | --- | --- | --- |',
  );
  for (const r of cpu.results)
    lines.push(
      `| ${r.name} | ${String(r.marks)} | ${ms(r.sceneMs.median)} | ${ms(r.modelMs.median)} | ${ms(r.viewMs.median)} | ${ms(r.inkMs.median)} | ${ms(r.presentMs.median)} | ${ms(r.orbitFrameMs.median)} | ${ms(r.firstFrameMs.median)} |`,
    );
  lines.push('');
}
if (worker) {
  lines.push(
    '### The CPU engine in a worker, on the page',
    '',
    `${worker.label}; ${worker.preset}; load after ${worker.loadAfter.join(' ')}.`,
    '',
    '| where it ran | frames drawn | longest gap between animation frames ms | long tasks (>= 50 ms) | their total ms | time to feed the drag ms |',
    '| --- | --- | --- | --- | --- | --- |',
  );
  for (const [k, r] of Object.entries(worker.rows))
    lines.push(
      `| ${k} | ${String(/** @type {any} */ (r).framesDrawn)} | ${String(/** @type {any} */ (r).maxFrameGapMs)} | ${String(/** @type {any} */ (r).longTasks)} | ${String(/** @type {any} */ (r).longTaskMs)} | ${String(/** @type {any} */ (r).driveMs)} |`,
    );
  lines.push('');
}
if (!existsSync(dir)) process.exit(1);
const cfg = (await resolveConfig(out)) ?? {};
writeFileSync(out, await format(lines.join('\n'), { ...cfg, filepath: out }));
console.log(`wrote ${out}`);
