/**
 * Presets: named partial parameter sets laid over the defaults, as the reference's `PRESETS`
 * (app23.js:L20–66, 45 presets), verbatim and in the same order. The golden images (tests/golden/)
 * are keyed by these names, so names must stay identical to the reference;
 * tests/unit/params.test.ts checks this file against app23.js.
 *
 * A preset is applied as the reference does (`Object.assign({}, DEF, PRESETS[name], { seed })`,
 * app23.js:L1549): the seed is kept.
 */
import { DEF, type Params } from './params';

export const PRESETS: Readonly<Record<string, Readonly<Partial<Params>>>> = {
  'Grand design': {},
  'Barred spiral': {
    bar: 0.85,
    barLen: 0.5,
    arms: 2,
    pitch: 16,
    ring: 0.25,
    ringR: 1.35,
    bulge: 0.18,
  },
  Flocculent: {
    arms: 5,
    pitch: 26,
    armStrength: 0.6,
    armWidth: 0.55,
    flocc: 0.8,
    bulge: 0.08,
    knots: 0.5,
    stroke: 'broken',
  },
  'Hand-drawn arms': { armStyle: 'drawn', arms: 3, pitch: 14, lines: 0.9, knots: 0.3 },
  'Tightly wound': { arms: 3, pitch: 9, armWidth: 0.28, bulge: 0.3, stroke: 'plain' },
  'Loose, open arms': {
    arms: 2,
    pitch: 38,
    armWidth: 0.3,
    bulge: 0.06,
    knots: 0.55,
    stroke: 'beaded',
  },
  Ringed: { arms: 0, ring: 0.9, ringR: 1.5, bar: 0.6, barLen: 0.55, bulge: 0.3, outline: 0.3 },
  'Disc, no arms': {
    arms: 0,
    bulge: 0.4,
    outline: 0.8,
    knots: 0.05,
    sparkle: 0.02,
    incl: 45,
    envelope: 0.7,
  },
  'Smooth, round': {
    arms: 0,
    bulge: 1,
    bulgeSize: 0.9,
    bulgeFlat: 0.95,
    halo: 0.25,
    knots: 0,
    sparkle: 0,
    lines: 0,
    incl: 10,
    envelope: 0.5,
  },
  'Cigar-shaped': {
    arms: 0,
    bulge: 1,
    bulgeSize: 0.9,
    bulgeFlat: 0.35,
    halo: 0.1,
    knots: 0,
    sparkle: 0,
    lines: 0,
    incl: 88,
  },
  'Edge-on with dust': {
    incl: 88,
    dust: 0.85,
    thick: 0.05,
    bulge: 0.3,
    arms: 2,
    lines: 0.5,
    stroke: 'plain',
  },
  'Merger: the Mice': {
    merger: 1,
    mRatio: 0.9,
    mPeri: 1.1,
    mStage: 0.9,
    mSpin1: 15,
    mSpin2: 30,
    incl: 35,
    pa: 120,
  },
  'Merger: long tails': {
    merger: 1,
    mRatio: 1,
    mPeri: 1.6,
    mStage: 2.6,
    mSpin1: 10,
    mSpin2: 160,
    incl: 55,
    pa: 40,
  },
  'Merger: minor, a stream': {
    merger: 1,
    mRatio: 0.15,
    mPeri: 1.2,
    mStage: 2.2,
    mSpin1: 30,
    mSpin2: 60,
    incl: 25,
    pa: 10,
  },
  'Merger: spiral meets elliptical': {
    merger: 1,
    mRatio: 0.7,
    mPeri: 1,
    mStage: 1.6,
    mSpin1: 20,
    mSpin2: 40,
    mType1: 'spiral',
    mArms1: 2,
    mType2: 'elliptical',
    mTilt: 20,
  },
  'Merger: dry (two ellipticals)': {
    merger: 1,
    mRatio: 0.8,
    mPeri: 0.9,
    mStage: 2.4,
    mType1: 'elliptical',
    mType2: 'elliptical',
    mFriction: 0.4,
    mTilt: 35,
  },
  'Merger: polar collision': {
    merger: 1,
    mRatio: 0.5,
    mPeri: 1.2,
    mStage: 1.4,
    mSpin1: 10,
    mSpin2: 85,
    mArms1: 3,
    mTilt: 80,
    mEcc: 1.1,
  },
  'Merger: three-armed pair': {
    merger: 1,
    mRatio: 0.9,
    mPeri: 1.3,
    mStage: 1.1,
    mSpin1: 25,
    mSpin2: 50,
    mArms1: 3,
    mArms2: 3,
    mBar1: 1,
  },
  'Layered: spiral beside a bright star': {
    arms: 2,
    pitch: 16,
    armStrength: 0.8,
    bar: 0,
    incl: 35,
    ovStar: 0.85,
    ovStarD: 1.7,
    ovStarA: 35,
    spikes: 0.8,
    starRings: 0.4,
    bleed: 0.5,
  },
  'Layered: barred spiral, satellite trail': {
    arms: 2,
    pitch: 20,
    bar: 0.8,
    barLen: 0.55,
    incl: 30,
    ovArtefact: 'trail',
  },
  'Layered: edge-on, star on top': {
    arms: 2,
    bulge: 0.25,
    incl: 86,
    dust: 0.7,
    ovStar: 0.7,
    ovStarD: 0.35,
    ovStarA: 120,
    spikes: 0.7,
  },
  'Layered: lensed merger': {
    merger: 1,
    mType1: 'spiral',
    mType2: 'elliptical',
    mStage: 1.5,
    lensOn: 1,
    lensR: 1.2,
    lensSrc: 0.05,
    lensSize: 0.14,
    lensQ: 0.8,
  },
  'Layered: ringed galaxy, ghost reflection': {
    arms: 2,
    ring: 0.7,
    ringR: 1.6,
    incl: 25,
    ovArtefact: 'ghost',
    spikes: 0.7,
  },
  'Star: bright, with spikes': {
    subject: 'star',
    starBright: 0.92,
    spikes: 0.9,
    starRings: 0.55,
    bleed: 0.65,
    field: 0.5,
    fgstars: 0.3,
  },
  'Star: faint': {
    subject: 'star',
    starBright: 0.35,
    spikes: 0.3,
    starRings: 0.1,
    bleed: 0,
    field: 0.6,
    fgstars: 0.35,
  },
  'Artefact: satellite trail': {
    subject: 'artefact',
    artefact: 'trail',
    starBright: 0.5,
    spikes: 0.5,
    field: 0.55,
  },
  'Artefact: ghost reflection': {
    subject: 'artefact',
    artefact: 'ghost',
    spikes: 0.7,
    starRings: 0.4,
    bleed: 0.4,
    field: 0.45,
  },
  'Artefact: cosmic rays': { subject: 'artefact', artefact: 'cosmic', field: 0.5 },
  'Merger: coalescing': {
    merger: 1,
    mRatio: 0.8,
    mPeri: 0.9,
    mStage: 4.5,
    mSpin1: 20,
    mSpin2: 120,
    mFriction: 0.8,
    incl: 40,
    pa: 70,
  },
  'Lens: Einstein ring': {
    arms: 0,
    bulge: 1,
    bulgeFlat: 0.85,
    incl: 88,
    sersicN: 4,
    re: 0.7,
    lines: 0,
    knots: 0,
    sparkle: 0,
    lensOn: 1,
    lensSrc: 0,
    lensShear: 0.02,
    lensR: 1.7,
    lensQ: 0.85,
    lensCore: 0.04,
    lensSize: 0.14,
    lensStars: 6000,
  },
  'Lens: Einstein cross (quasar)': {
    arms: 0,
    bulge: 1,
    bulgeFlat: 0.7,
    incl: 88,
    sersicN: 4,
    re: 0.6,
    lines: 0,
    knots: 0,
    sparkle: 0,
    lensOn: 1,
    lensSource: 'quasar',
    lensSrc: 0.05,
    lensSrcA: 40,
    lensShear: 0.03,
    lensR: 1.6,
    lensQ: 0.7,
    lensCore: 0.03,
    lensSize: 0.09,
  },
  'Lens: galaxy cluster': {
    arms: 0,
    bulge: 1,
    bulgeFlat: 0.7,
    incl: 88,
    sersicN: 5,
    re: 0.95,
    lines: 0,
    knots: 0,
    sparkle: 0,
    lensOn: 1,
    lensCluster: 1,
    lensR: 1.15,
    lensShear: 0.02,
    lensStars: 10000,
    field: 0.85,
  },
  'Lens: double Einstein ring': {
    arms: 0,
    bulge: 1,
    bulgeFlat: 0.9,
    incl: 88,
    sersicN: 4,
    re: 0.65,
    lines: 0,
    knots: 0,
    sparkle: 0,
    lensOn: 1,
    lensDouble: 1,
    lensSrc: 0.01,
    lensQ: 0.9,
    lensR: 1.45,
    lensSize: 0.11,
    lensShear: 0.01,
    lensStars: 7000,
  },
  'Lens: giant arc': {
    arms: 0,
    bulge: 1,
    bulgeFlat: 0.75,
    incl: 88,
    sersicN: 4,
    re: 0.7,
    lines: 0,
    knots: 0,
    sparkle: 0,
    lensOn: 1,
    lensSrc: 0.2,
    lensSrcA: 60,
    lensShear: 0.05,
    lensR: 1.8,
    lensSize: 0.15,
  },
  'Lens: a quad': {
    arms: 0,
    bulge: 1,
    bulgeFlat: 0.7,
    incl: 88,
    sersicN: 4,
    re: 0.6,
    lines: 0,
    knots: 0,
    sparkle: 0,
    lensOn: 1,
    lensSrc: 0.05,
    lensSrcA: 35,
    lensShear: 0.05,
    lensShearA: 10,
    lensR: 1.6,
    lensSize: 0.07,
    lensStars: 7000,
    lensQ: 0.65,
    lensCore: 0.02,
  },
  'Deep field': {
    field: 1,
    arms: 0,
    bulge: 1,
    bulgeFlat: 0.8,
    incl: 88,
    sersicN: 4,
    re: 0.7,
    lines: 0,
    knots: 0,
    sparkle: 0,
    fgstars: 0.4,
  },
  'A sketch, lensed': {
    arms: 0,
    bulge: 1,
    bulgeFlat: 0.8,
    incl: 88,
    sersicN: 4,
    re: 0.6,
    lines: 0,
    knots: 0,
    sparkle: 0,
    lensOn: 1,
    lensSource: 'drawing',
    lensSrc: 0.3,
    lensSrcA: 50,
    lensShear: 0.05,
    lensR: 1.45,
    lensSize: 0.4,
    lensStars: 4200,
    field: 0.5,
  },
  'Sketches, torn apart': {
    merger: 1,
    mWarp: 1,
    mRatio: 0.9,
    mPeri: 1.1,
    mStage: 1.3,
    mSpin1: 15,
    mSpin2: 30,
    incl: 30,
    pa: 100,
  },
  'Radio jet': {
    arms: 0,
    bulge: 1,
    bulgeFlat: 0.9,
    incl: 88,
    sersicN: 4,
    re: 0.7,
    lines: 0,
    knots: 0,
    sparkle: 0,
    jet: 1,
    field: 0.4,
  },
  'Stellar streams': {
    arms: 0,
    bulge: 1,
    bulgeFlat: 0.85,
    incl: 88,
    sersicN: 3.5,
    re: 0.6,
    stars: 7000,
    lines: 0,
    knots: 0,
    sparkle: 0,
    streams: 1,
    field: 0.3,
  },
  'Dusty spiral': { arms: 2, pitch: 20, dustLines: 1, bubbles: 0.8, knots: 0.6, incl: 35 },
  'Hand wobble': { arms: 3, pitch: 22, distort: 0.8, bubbles: 0.6 },
  'Shell galaxy': {
    arms: 0,
    bulge: 1,
    bulgeFlat: 0.85,
    incl: 88,
    sersicN: 3.5,
    re: 0.6,
    stars: 9000,
    lines: 0,
    knots: 0,
    sparkle: 0,
    shellsOn: 1,
    shellTime: 70,
    shellAxis: 25,
  },
  'Plates slipped': { plates: 'slip', arms: 2, pitch: 20 },
  'Stellar populations': {
    plates: 'colour',
    arms: 2,
    pitch: 22,
    knots: 0.6,
    sparkle: 0.7,
    bulge: 0.25,
  },
};

export const PRESET_NAMES: readonly string[] = Object.keys(PRESETS);

/** The full parameters of a preset at a seed (the reference keeps the current seed). */
export function presetParams(
  name: string,
  seed: number = DEF.seed,
  extra: Partial<Params> = {},
): Params {
  const p = PRESETS[name];
  if (!p) throw new Error(`unknown preset ${JSON.stringify(name)}`);
  return { ...DEF, ...p, seed, ...extra };
}

/** The UI's families, by name prefix (app23.js:L1544). */
export function presetFamily(
  name: string,
): 'galaxy' | 'merger' | 'lens' | 'star' | 'artefact' | 'layered' | 'creative' {
  if (name.startsWith('Merger:') || name === 'Sketches, torn apart') return 'merger';
  if (name.startsWith('Lens:') || name === 'A sketch, lensed') return 'lens';
  if (name.startsWith('Star:')) return 'star';
  if (name.startsWith('Artefact:')) return 'artefact';
  if (name.startsWith('Layered:')) return 'layered';
  const creative = [
    'Deep field',
    'Radio jet',
    'Stellar streams',
    'Dusty spiral',
    'Hand wobble',
    'Shell galaxy',
    'Plates slipped',
    'Stellar populations',
  ];
  return creative.includes(name) ? 'creative' : 'galaxy';
}
