/**
 * The shared RNG vectors on the GPU (ADR 0004): tests/vectors/rng.json, generated by
 * src/core/rng.ts, against src/shaders/common/rng.wgsl in a compute shader. pcg4d, u32 and
 * uniform draws must match bit for bit; the Gaussian (log, sqrt, cos) within a tolerance.
 */
import rngTest from './rng-test.wgsl';
import vectorsJson from '../vectors/rng.json';
import type { RngVectors } from '../vectors/rng-cases';
import { adapterName, device, run } from './harness';

const vectors = vectorsJson as RngVectors;
/**
 * Gaussian tolerance, absolute for |z| <= 1 and relative above. WGSL allows `cos` an absolute
 * error of 2^-11 on [-π, π] (and `log`, `sqrt` a few ULP), and r = sqrt(-2 ln(1 - u1)) is at most
 * about 5.6, so the bound is about 2^-11 · 5.6 ≈ 2.7e-3.
 */
const GAUSS_TOL = 2.7e-3;

run('rng vectors (CPU = GPU)', async () => {
  const { adapter, device: dev } = await device();
  const n = vectors.keys.length;
  const keys = dev.createBuffer({
    size: n * 16,
    usage: GPUBufferUsage.STORAGE,
    mappedAtCreation: true,
  });
  new Uint32Array(keys.getMappedRange()).set(vectors.keys.flat());
  keys.unmap();
  const results = dev.createBuffer({
    size: n * 32,
    usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_SRC,
  });
  const read = dev.createBuffer({
    size: n * 32,
    usage: GPUBufferUsage.COPY_DST | GPUBufferUsage.MAP_READ,
  });
  const module = dev.createShaderModule({ code: rngTest });
  const info = await module.getCompilationInfo();
  if (info.messages.some((m) => m.type === 'error'))
    throw new Error(info.messages.map((m) => m.message).join('\n'));
  const pipeline = dev.createComputePipeline({
    layout: 'auto',
    compute: { module, entryPoint: 'main' },
  });
  const bind = dev.createBindGroup({
    layout: pipeline.getBindGroupLayout(0),
    entries: [
      { binding: 0, resource: { buffer: keys } },
      { binding: 1, resource: { buffer: results } },
    ],
  });
  const enc = dev.createCommandEncoder();
  const pass = enc.beginComputePass();
  pass.setPipeline(pipeline);
  pass.setBindGroup(0, bind);
  pass.dispatchWorkgroups(Math.ceil(n / 64));
  pass.end();
  enc.copyBufferToBuffer(results, 0, read, 0, n * 32);
  dev.queue.submit([enc.finish()]);
  await read.mapAsync(GPUMapMode.READ);
  const u = new Uint32Array(read.getMappedRange().slice(0));
  read.unmap();
  const fl = new Float32Array(u.buffer);

  let pcgBad = 0;
  let u32Bad = 0;
  let unitBad = 0;
  let gaussBad = 0;
  let gaussMax = 0;
  const firstBad: string[] = [];
  for (let i = 0; i < n; i++) {
    const want = vectors.pcg4d[i] ?? [];
    const got = [...u.subarray(8 * i, 8 * i + 4)];
    if (got.some((x, k) => x !== want[k])) {
      pcgBad++;
      if (firstBad.length < 3)
        firstBad.push(
          `key ${JSON.stringify(vectors.keys[i])}: ${JSON.stringify(got)} ≠ ${JSON.stringify(want)}`,
        );
    }
    if (u[8 * i + 4] !== vectors.u32[i]) u32Bad++;
    if (u[8 * i + 5] !== vectors.unitBits[i]) unitBad++;
    const g = fl[8 * i + 6] ?? NaN;
    const w = vectors.gauss[i] ?? NaN;
    const err = Math.abs(g - w) / Math.max(1, Math.abs(w));
    gaussMax = Math.max(gaussMax, err);
    if (!(err <= GAUSS_TOL)) gaussBad++;
  }
  const pass_ = pcgBad + u32Bad + unitBad + gaussBad === 0;
  return {
    pass: pass_,
    lines: [
      `adapter: ${adapterName(adapter)}`,
      `${String(n)} keys: pcg4d mismatches ${String(pcgBad)}, u32 ${String(u32Bad)}, uniform bits ${String(unitBad)} (bit-exact required)`,
      `gaussian: max error ${gaussMax.toExponential(2)} (tolerance ${GAUSS_TOL.toExponential(1)}), ${String(gaussBad)} over`,
      ...firstBad,
    ],
    data: { n, pcgBad, u32Bad, unitBad, gaussBad, gaussMax },
  };
});
