/**
 * The shared RNG test vectors (tests/vectors/rng.json): their keys and how they are computed.
 * Regenerate with `npm run vectors`, which runs tests/unit/rng.test.ts with ROSSE_WRITE_VECTORS=1.
 * The file is committed: the GPU test (tests/gpu/rng.ts) and any later implementation are checked
 * against it, so it must only change on purpose.
 */
import { pcg4d, randGauss, randU32, u32ToUnit } from '../../src/core/rng';

export interface RngVectors {
  description: string;
  /** [seed, stream, index, draw] */
  keys: [number, number, number, number][];
  /** pcg4d(key), all four words */
  pcg4d: [number, number, number, number][];
  /** randU32(key) */
  u32: number[];
  /** the bits of randF32(key) as an f32, as a u32 */
  unitBits: number[];
  /** randGauss(key): compared within a tolerance */
  gauss: number[];
}

/** Edge cases, then keys spread by the hash itself (so the list is reproducible). */
export function rngKeys(): [number, number, number, number][] {
  const M = 0xffffffff;
  const keys: [number, number, number, number][] = [
    [0, 0, 0, 0],
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1],
    [M, M, M, M],
    [M, 0, 0, 0],
    [0, 0, 0, M],
    [0x80000000, 0x7fffffff, 0x55555555, 0xaaaaaaaa],
    [7, 2, 0, 0],
    [7, 2, 1, 0],
    [4242, 2, 123456, 29],
  ];
  for (let i = 0; i < 244; i++) {
    const h = pcg4d(0x5eed, 0, i, 0);
    // small seeds and streams, as used in practice, and some full-range keys
    keys.push(
      i % 2 ? [h[0] % 10000, h[1] % 16, h[2] % 200000, h[3] % 64] : [h[0], h[1], h[2], h[3]],
    );
  }
  return keys;
}

export function computeRngVectors(): RngVectors {
  const keys = rngKeys();
  const bits = new Uint32Array(1);
  const fl = new Float32Array(bits.buffer);
  return {
    description:
      'Shared RNG vectors (ADR 0004): pcg4d keyed by [seed, stream, index, draw]. Generated by src/core/rng.ts (npm run vectors).',
    keys,
    pcg4d: keys.map((k) => pcg4d(...k)),
    u32: keys.map((k) => randU32(...k)),
    unitBits: keys.map((k) => {
      fl[0] = u32ToUnit(randU32(...k));
      return bits[0] ?? 0;
    }),
    gauss: keys.map((k) => randGauss(...k)),
  };
}
